Update keepalive.yml

diff --git a/.github/workflows/keepalive.yml b/.github/workflows/keepalive.yml
--- a/.github/workflows/keepalive.yml
+++ b/.github/workflows/keepalive.yml
@@ -25,5 +25,6 @@ jobs:
           git commit -m "Keep-Alive"
           git push origin master
         else
-          echo "Oops, seems the keep-alive failed!";
+          echo "Oops, seems the keep-alive failed!"
+          exit 1
         fi
